final surahMeaningsInEnglish = [
  "The Opening",
  "The Cow",
  "The Family of Imran",
  "The Women",
  "The Table Spread",
  "The Cattle",
  "The Heights",
  "The Spoils of War",
  "The Repentance",
  "Jonah",
  "Hud",
  "Joseph",
  "The Thunder",
  "Abraham",
  "The Rocky Tract",
  "The Bee",
  "The Night Journey",
  "The Cave",
  "Mary",
  "Ta-Ha",
  "The Prophets",
  "The Pilgrimage",
  "The Believers",
  "The Light",
  "The Criterion",
  "The Poets",
  "The Ant",
  "The Stories",
  "The Spider",
  "The Romans",
  "Luqman",
  "The Prostration",
  "The Combined Forces",
  "Sheba",
  "The Originator",
  "Ya Sin",
  "Those Who Set The Ranks",
  "The Letter \"Saad\"",
  "The Troops",
  "The Forgiver",
  "Explained in Detail",
  "The Consultation",
  "The Ornaments of Gold",
  "The Smoke",
  "The Crouching",
  "The Wind-Curved Sandhills",
  "Muhammad",
  "The Victory",
  "The Rooms",
  "The Letter \"Qaf\"",
  "The Winnowing Winds",
  "The Mount",
  "The Star",
  "The Moon",
  "The Beneficent",
  "The Inevitable",
  "The Iron",
  "The Pleading Woman",
  "The Exile",
  "The Tested One",
  "The Ranks",
  "The Congregation, Friday",
  "The Hypocrites",
  "The Mutual Disillusionment",
  "The Divorce",
  "The Prohibition",
  "The Sovereignty",
  "The Pen",
  "The Reality",
  "The Ascending Stairways",
  "Noah",
  "The Jinn",
  "The Enshrouded One",
  "The Cloaked One",
  "The Resurrection",
  "The Man",
  "The Emissaries",
  "The Tidings",
  "Those Who Drag Forth",
  "He Frowned",
  "The Overthrowing",
  "The Cleaving Asunder",
  "The Defrauding",
  "The Splitting Open",
  "The Mansions of the Stars",
  "The Morning Star",
  "The Most High",
  "The Overwhelming",
  "The Dawn",
  "The City",
  "The Sun",
  "The Night",
  "The Morning Hours",
  "The Relief",
  "The Fig",
  "The Clot",
  "The Power",
  "The Clear Proof",
  "The Earthquake",
  "The Courser",
  "The Calamity",
  "The Rivalry in World Increase",
  "The Declining Day",
  "The Traducer",
  "The Elephant",
  "Quraysh",
  "Small Kindnesses",
  "The Abundance",
  "The Disbelievers",
  "The Divine Support",
  "The Palm Fiber",
  "The Sincerity",
  "The Daybreak",
  "Mankind",
];
