final surahMeaningsInEnglish = [
  'The Opening',
  'The Cow',
  'The Family of Imran',
  'The Women',
  'The Table Spread',
  'The Cattle',
  'The Heights',
  'The Spoils of War',
  'The Repentance',
  'Jonah',
  'Hud',
  'Joseph',
  'Thunder',
  'Abraham',
  'Al-Hijr (The Stoneland)',
  'The Bee',
  'The Night Journey',
  'The Cave',
  'Mary',
  'Ta-Ha',
  'The Prophets',
  'The Pilgrimage',
  'The Believers',
  'The Light',
  'The Criterion',
  'The Poets',
  'The Ants',
  'The Narration',
  'The Spider',
  'The Romans',
  'Luqman',
  'The Prostration',
  'The Confederates',
  'Sheba',
  'Originator',
  'Ya-Sin',
  'Those Who Set The Ranks',
  'Sad',
  'The Troops',
  'The Forgiver',
  'Explained in Detail',
  'Consultation',
  'Decoration',
  'Smoke',
  'The Kneeling',
  'The Dunes',
  'Muhammad',
  'Victory',
  'The Apartments',
  'Qaf',
  'The Winnowing Winds',
  'The Mount',
  'The Star',
  'The Moon',
  'The Most Merciful',
  'The Inevitable Event',
  'Iron',
  'The Pleading Woman',
  'The Exile',
  'The Examined One',
  'The Ranks',
  'Friday',
  'The Hypocrites',
  'Mutual Disillusionment',
  'Divorce',
  'Prohibition',
  'Dominion',
  'The Pen',
  'The Reality',
  'The Ascending Stairways',
  'Noah',
  'The Jinn',
  'The Enwrapped One',
  'The Cloaked One',
  'Resurrection',
  'Man',
  'The Emissaries',
  'The Tiding',
  'Those Who Drag Forth',
  'He Frowned',
  'The Overthrowing',
  'The Folding Up',
  'The Cleaving Asunder',
  'Defrauding',
  'The Splitting Open',
  'The Mansions of the Stars',
  'The Nightcomer',
  'The Most High',
  'The Overwhelming Event',
  'Daybreak',
  'The City',
  'The Sun',
  'The Night',
  'The Pledges',
  'The Country',
  'The Fig',
  'The Clot',
  'The Power',
  'The Evidence',
  'Earthquake',
  'The Courser',
  'The Calamity',
  'Competition',
  'The Reproduction of Wealth',
  'Time',
  'The Hamza',
  'The Elephant',
  'Quraysh',
  'Small Kindnesses',
  'Abundance',
  'The Disbelievers',
  'Victory',
  'Help',
  'Palm Fiber',
  'Sincerity',
  'Daybreak',
  'Mankind',
];
